config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :addresses

  root 'people#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person

  validates :kind, :street_address, :city, :state, :zip, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses

  accepts_nested_attributes_for :addresses,
        :reject_if => proc {|attributes|
          attributes.all? {|k,v| v.blank?}
        }

  validates :name, presence: true
  validates_associated :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
    3.times { @person.addresses.build }
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render "new"
    end
  end

  def show
    @person = People.find(params[:id])
  end

  private

  def person_params
    params.require(:person).permit(:name, addresses_attributes: [:kind, :street_address, :city, :state, :zip])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>Address Book</h1>

<ul>
  <% @people.each do |person| %>
    <h3><%= person.name %></h3>
    <ul>
      <% person.addresses.each do |address| %>
      <li><%= address.kind %>: <%= address.street_address %>, <%= address.city %>, <%= address.state %>, <%= address.zip %></li>
      <% end %>
    </ul>
  <% end %>
</ul>

<%= link_to 'Create New Person', new_person_path %>

app/views/people/new.html.erb
<h2>Create a new person</h2>

<%= form_for(@person) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <br>
  Addresses:
  <ol>
    <%= f.fields_for :addresses do |a| %>
      <li>
        <p>
          <%= a.label :kind %>
          <%= a.text_field :kind %>
        </p>
        <p>
          <%= a.label :street_address %>
          <%= a.text_field :street_address %>
        </p>
        <p>
          <%= a.label :city %>
          <%= a.text_field :city %>
        </p>
        <p>
          <%= a.label :state %>
          <%= a.text_field :state %>
        </p>
        <p>
          <%= a.label :zip %>
          <%= a.text_field :zip %>
        </p>
      </li>
    <% end %>
  </ol>
  <p>
    <%= f.submit %>
  </p>
<% end %>